#!/bin/sh
DAEMON=/usr/sbin/hostapd
NAME=hostapd
DESC="HOSTAP Daemon"

CONFIN="/etc/hostapd.conf"
CONFOU="/tmp/hostapd-local.ELcyOo.conf"
ARGS="$CONFOU -B"

test -f "$DAEMON" || exit 0

set -e

if [ ! -f "$CONFOU" ]
then
  HMAC=`ifconfig wlan0 | grep HWaddr | cut -d : -f 5-7 | tr '[:upper:]' '[:lower:]' | tr -d '[:space:]:'`
  SSID="ssid=cuddlebot-$HMAC"
  sed "s/ssid=cuddlebot/$SSID/" "$CONFIN" > "$CONFOU"
fi

case "$1" in
    start)
  echo -n "Starting $DESC: "
  start-stop-daemon -S -x $DAEMON -- $ARGS
  echo "$NAME."
  ;;
    stop)
  echo -n "Stopping $DESC: "
  start-stop-daemon -K -x $DAEMON
  echo "$NAME."
  ;;
    restart)
  $0 stop
  $0 start
  ;;
    reload)
  echo -n "Reloading $DESC: "
  killall -HUP $(basename ${DAEMON})
  echo "$NAME."
  ;;
    *)
  echo "Usage: $0 {start|stop|restart|reload}"
  exit 1
  ;;
esac

exit 0
