#!/bin/sh
FOREVER=/opt/tamer-control/node_modules/.bin/forever
DAEMON=/opt/tamer-control/node_modules/.bin/tamer-control
PID=/var/run/tamer-control
NAME=tamer-control
DESC="Tamer Control Web Service"

test -f $DAEMON || exit 0

[ -r /etc/default/tamer-control ] && . /etc/default/tamer-control
[ -d /var/log/tamer-control ] || mkdir -p /var/log/tamer-control
[ -d /var/run/tamer-control ] || mkdir -p /var/run/tamer-control

set -e

case "$TAMER_CONTROL_ENABLE" in
  [Nn]*)
    exit 0
    ;;
esac

case "$1" in
  start)
    echo "Starting $DESC: $NAME"
    $FOREVER start \
      --minUptime 1000 --spinSleepTime 1000 \
      --plain -p $PID -a \
      -l /var/log/tamer-control/forever.log \
      -o /var/log/tamer-control/out.log \
      -e /var/log/tamer-control/err.log \
      $DAEMON $PORT
    ;;
  stop)
    echo "Stopping $DESC: $NAME"
    $FOREVER stop --plain -p $PID $DAEMON
    ;;
  restart)
    echo "Restarting $DESC: $NAME"
    $FOREVER restart --plain -p $PID $DAEMON
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
